image:
  repository: ghcr.io/evoluciona2023/patrones-ms
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

livenessProbe:
  path: /actuator/health/liveness
readinessProbe:
  path: /actuator/health/readiness

env: []

ingress:
  enabled: true
  host: patrones-ms.localtest.me
  tls: false
  tlsSecret: patrones-ms-tls
